### ISSUE TITLE
Site To Cloud User Story

### ISSUE THREAD

**Issue by ShutingQing** [camaraproject/SiteToCloudVPN#4]
**Problem description**
Add the user story of Site To Cloud VPN API. 

**Expected action**

**Additional context**

**Comment by ShutingQing** [comment]
Linked to https://github.com/camaraproject/SiteToCloudVPN/pull/1

**Comment by DanXu-ChinaTelecom** [comment]
LGTM

**Comment by ShutingQing** [comment]
Finished
