### ISSUE TITLE
S2C VPN_API Yaml

### ISSUE THREAD

**Issue by DanXu-ChinaTelecom** [camaraproject/SiteToCloudVPN#9]
**Problem description**

Initial version of API Yaml of Site to Cloud VPN API.
**Possible evolution**

None
**Alternative solution**

None
**Additional context**

None

**Comment by chinaunicomyangfan** [comment]
@DanXu-ChinaTelecom The yaml file seems to have some errors, and this website should be able to help you check the format of the yaml file
[https://editor.swagger.io/](https://editor.swagger.io/)
![image](https://github.com/camaraproject/SiteToCloudVPN/assets/130550398/bd83d867-e39e-4bb3-8cb7-a8cf989f4a9f)

**Comment by DanXu-ChinaTelecom** [comment]
I use the http://editor-next.swagger.io/, maybe there is an incompatibility. Anyway, I'll update the format of the yaml file using https://editor.swagger.io/
